# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal  Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
require 'set'

def trian(n)
  n * (n + 1.0) / 2
end

def penta(n)
  n * (3.0 * n - 1) / 2
end

def hexag(n)
  n * (2.0 * n - 1)
end
# p trian(285), penta(165), hexag(143)

t1 = Set.new [*(2..100_000)].map { |e| trian(e) }
p1 = Set.new [*(2..100_000)].map { |e| penta(e) }
h1 = Set.new [*(2..100_000)].map { |e| hexag(e) }

p (t1 & p1 & h1).to_a.find { |e| e > 40_755 }
