# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
# The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
# 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
# difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
require 'set'

def penta(n)
  n * (3.0 * n - 1) / 2
end

valores = Set.new
pentags = {}

[*(1..10_000)].each do |n|
  valores << penta(n)
  pentags[n] = penta(n)
end

pentags.keys.combination(2).each do |a, b|
  s = pentags[a] + pentags[b]
  d = (pentags[a] - pentags[b]).abs
  puts "#{a} #{b} => #{d}" if valores.include?(s) && valores.include?(d)
end
